name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
        - uses: "actions/checkout@11d5960a326750d5838078e36cf38b85af677262"
        - uses: "home-assistant/actions/hassfest@a7c616ce81ccda50150bf1595786c71b1883fabb"
