name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    name: Home Assistant tests (Python 3.14)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: "3.14"
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          version: "0.12.3"
          enable-cache: true
      - run: uv lock --upgrade
      - run: uv run --frozen --group test ruff check .
      - run: uv run --frozen --group test pytest -v
